#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const DOCS_DIR = path.join(ROOT_DIR, 'docs');
const OUTPUT_FILE = path.join(DOCS_DIR, 'index-catalog.md');

const SECTIONS = [
  { dir: 'concepts', label: 'Concepts' },
  { dir: 'entities', label: 'Entities' },
  { dir: 'ideas', label: 'Ideas' },
  { dir: 'findings', label: 'Findings' },
  { dir: 'readings', label: 'Readings' },
  { dir: 'comparisons', label: 'Comparisons' },
];

// Reuse the same frontmatter parser
function parseFrontmatter(content) {
  const fmRegex = /^---\r?\n([\s\S]*?)\r?\n---/;
  const match = content.match(fmRegex);
  if (!match) return {};
  const fm = {};
  for (const line of match[1].split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const colonIdx = trimmed.indexOf(':');
    if (colonIdx === -1) continue;
    const key = trimmed.substring(0, colonIdx).trim();
    let value = trimmed.substring(colonIdx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (value.startsWith('[') && value.endsWith(']')) {
      const inner = value.slice(1, -1).trim();
      fm[key] = inner ? inner.split(',').map(s => s.trim().replace(/^["']|["']$/g, '')) : [];
    } else {
      fm[key] = value;
    }
  }
  return fm;
}

function getPages(dirPath) {
  let files = [];
  try {
    files = fs.readdirSync(dirPath).filter(f => f.endsWith('.md') && f !== 'index.md');
  } catch {
    return [];
  }

  return files.map(file => {
    const fullPath = path.join(dirPath, file);
    const content = fs.readFileSync(fullPath, 'utf-8');
    const fm = parseFrontmatter(content);
    return {
      filename: file,
      slug: file.replace(/\.md$/, ''),
      title: fm.title || file.replace(/\.md$/, ''),
      domain: fm.domain || 'general',
      tags: Array.isArray(fm.tags) ? fm.tags : [],
      updated: fm.updated || '1970-01-01',
      status: fm.status || 'active'
    };
  }).sort((a, b) => a.title.localeCompare(b.title));
}

function generate() {
  let total = 0;
  let output = '# Index Catalog\n\n';
  output += '> Complete catalog of all wiki pages. Auto-generated by `scripts/generate-catalog.js`.\n';
  output += `> Last updated: ${new Date().toISOString().split('T')[0]} | Total pages: `;

  const sectionData = [];
  for (const section of SECTIONS) {
    const dirPath = path.join(DOCS_DIR, section.dir);
    const pages = getPages(dirPath);
    sectionData.push({ section, pages });
    total += pages.length;
  }

  output += `${total}\n\n`;

  for (const { section, pages } of sectionData) {
    output += `## ${section.label}\n\n`;
    if (pages.length === 0) {
      output += '*No pages yet*\n\n';
    } else {
      for (const page of pages) {
        output += `- [[${page.slug}]] — ${page.domain}`;
        if (page.tags.length > 0) {
          output += ` · \`${page.tags.join('`, `')}\``;
        }
        if (page.status === 'draft') {
          output += ` · *draft*`;
        }
        output += '\n';
      }
      output += '\n';
    }
  }

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`✓ Catalog generated: ${total} pages across ${SECTIONS.length} sections`);
  console.log(`✓ Saved to: ${OUTPUT_FILE}`);
}

generate();