#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { DOCS_DIR, CONTENT_DIRS, parseFrontmatter } = require('./lib');

const OUTPUT_FILE = path.join(DOCS_DIR, 'index-catalog.md');

const SECTIONS = [
  { dir: 'concepts', label: 'Concepts' },
  { dir: 'entities', label: 'Entities' },
  { dir: 'ideas', label: 'Ideas' },
  { dir: 'findings', label: 'Findings' },
  { dir: 'readings', label: 'Readings' },
  { dir: 'comparisons', label: 'Comparisons' },
  { dir: 'references', label: 'References' },
];

function getPages(dirPath) {
  let files = [];
  try {
    files = fs.readdirSync(dirPath).filter(f => f.endsWith('.md') && f !== 'index.md');
  } catch { return []; }

  return files.map(file => {
    const content = fs.readFileSync(path.join(dirPath, file), 'utf-8');
    const fm = parseFrontmatter(content) || {};
    return {
      slug: file.replace(/\.md$/, ''),
      title: fm.title || file.replace(/\.md$/, ''),
      domain: fm.domain || 'general',
      tags: Array.isArray(fm.tags) ? fm.tags : [],
      updated: fm.updated || '1970-01-01',
      status: fm.status || 'active',
      reviewed: fm.reviewed || null
    };
  }).sort((a, b) => a.title.localeCompare(b.title));
}

function generate() {
  let total = 0;
  const sectionData = [];

  for (const section of SECTIONS) {
    const pages = getPages(path.join(DOCS_DIR, section.dir));
    sectionData.push({ section, pages });
    total += pages.length;
  }

  let output = '# Index Catalog\n\n';
  output += '> Complete catalog of all wiki pages. Auto-generated by `scripts/generate-catalog.js`.\n';
  output += `> Last updated: ${new Date().toISOString().split('T')[0]} | Total pages: ${total}\n\n`;

  for (const { section, pages } of sectionData) {
    output += `## ${section.label}\n\n`;
    if (pages.length === 0) {
      output += '*No pages yet*\n\n';
    } else {
      for (const page of pages) {
        output += `- [[${page.slug}]] — ${page.domain}`;
        if (page.tags.length > 0) output += ` · \`${page.tags.join('`, `')}\``;
        if (page.status === 'draft') output += ` · *draft*`;
        if (page.reviewed) output += ` · ✓ ${page.reviewed}`;
        output += '\n';
      }
      output += '\n';
    }
  }

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`✓ Catalog generated: ${total} pages across ${SECTIONS.length} sections`);
  console.log(`✓ Saved to: ${OUTPUT_FILE}`);
}

generate();
